<Project>
  <PropertyGroup>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <Company>Bastion</Company>
    <Product>Bastion — Application Lock</Product>
    <Authors>Bastion</Authors>
    <Copyright>Copyright © 2026 Bastion</Copyright>
    <NeutralLanguage>en</NeutralLanguage>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>
</Project>
