namespace Bastion.Ui.Localization;

/// <summary>
/// All user-facing strings in English and Brazilian Portuguese. Keys are stable
/// identifiers; format strings use {0} placeholders. Missing keys fall back to
/// English, then to the key itself, so the UI never shows blanks.
/// </summary>
public static class Strings
{
    public static string Get(string key, string lang)
    {
        var table = lang == "pt" ? Pt : En;
        if (table.TryGetValue(key, out var v)) return v;
        if (En.TryGetValue(key, out var e)) return e;
        return key;
    }

    public static readonly Dictionary<string, string> En = new()
    {
        // Common
        ["Common_Cancel"] = "Cancel",
        ["Common_Confirm"] = "Confirm",
        ["Common_Save"] = "Save",
        ["Common_Remove"] = "Remove",
        ["Common_Ok"] = "OK",
        ["Common_Done"] = "Done",
        ["Common_Back"] = "Back",
        ["Common_Continue"] = "Continue",
        ["Common_Skip"] = "Skip",
        ["Common_Change"] = "Change",
        ["Common_SetUp"] = "Set up",
        ["Common_Manage"] = "Manage",
        ["Common_Clear"] = "Clear",
        ["Common_Pause"] = "Pause",

        // Gatekeeper
        ["GK_Subtitle"] = "This application is protected. Enter your password to open it.",
        ["GK_Placeholder"] = "Password",
        ["GK_Unlock"] = "Unlock",
        ["GK_Verifying"] = "Verifying…",
        ["GK_Identity"] = "Identity confirmed",
        ["GK_UseHello"] = "Use Windows Hello",
        ["GK_Footer"] = "Protected by Bastion",
        ["GK_Locked"] = "Locked",
        ["GK_UnavailableSub"] = "Protection is temporarily unavailable. Please try again in a moment.",
        ["GK_UnavailableErr"] = "The protection service is not responding.",
        ["GK_Incorrect"] = "Incorrect password.",
        ["GK_HelloFailed"] = "Windows Hello was not confirmed.",
        ["GK_CouldNotOpen"] = "Could not open the application.",
        ["GK_TooMany"] = "Too many attempts. Try again in {0}s.",

        // Nav / shell
        ["Nav_Home"] = "Home",
        ["Nav_Apps"] = "Applications",
        ["Nav_Activity"] = "Activity",
        ["Nav_Settings"] = "Settings",
        ["Status_Active"] = "Protection active",
        ["Status_Offline"] = "Service offline",
        ["Status_NoApps"] = "No apps protected",
        ["Status_Paused"] = "Protection paused",
        ["GlobalProtection"] = "Global protection",
        ["Banner_ServiceDown"] = "The Bastion protection service is not responding. Protection may be inactive.",
        ["Tip_Minimize"] = "Minimize",
        ["Tip_CloseTray"] = "Close to tray",

        // Tray
        ["Tray_Open"] = "Open Bastion",
        ["Tray_RelockAll"] = "Re-lock all apps now",
        ["Tray_Settings"] = "Settings",
        ["Tray_Exit"] = "Exit console (protection stays active)",
        ["Tray_Tooltip"] = "Bastion — Application Lock",

        // Home
        ["Home_CountNone"] = "Nothing protected yet",
        ["Home_CountOne"] = "1 app protected",
        ["Home_CountN"] = "{0} apps protected",
        ["Home_SubNone"] = "Choose an app and it won't open without your password.",
        ["Home_SubSome"] = "These apps require your password before they open.",
        ["Home_Protect"] = "Protect an application",
        ["Home_ProtectedApps"] = "Protected applications",
        ["Home_EmptyTitle"] = "Nothing is protected yet",
        ["Home_EmptySub"] = "Add your first app to require your password before it opens.",
        ["Home_Recent"] = "Recent activity",
        ["Home_NoActivity"] = "No activity yet.",

        // Status pills / policy descriptions
        ["Pill_Paused"] = "Paused",
        ["Pill_Unlocked"] = "Unlocked now",
        ["Pill_Protected"] = "Protected",
        ["Policy_Always"] = "Ask every time it opens",
        ["Policy_UntilClose"] = "Locked again when it closes",
        ["Policy_Minutes"] = "Stays unlocked for {0} min",
        ["Policy_Session"] = "Unlocked until you sign out",

        // Applications page
        ["Apps_Search"] = "Search protected apps…",
        ["Apps_Add"] = "Protect an app",
        ["Apps_EmptyTitle"] = "No protected apps",
        ["Apps_EmptySub"] = "Use “Protect an app” to add your first one.",
        ["Tip_OnOff"] = "Protection on/off",
        ["Tip_Configure"] = "Configure",
        ["Tip_OpenLocation"] = "Open file location",
        ["Tip_Remove"] = "Remove protection",
        ["Confirm_PauseAppTitle"] = "Pause protection for {0}?",
        ["Confirm_PauseAppMsg"] = "It will open without a password until you turn protection back on.",
        ["Confirm_RemoveTitle"] = "Remove protection from {0}?",
        ["Confirm_RemoveMsg"] = "This app will open normally, without asking for your password.",
        ["Err_UpdateTitle"] = "Couldn't update",
        ["Err_RemoveTitle"] = "Couldn't remove",
        ["Err_Generic"] = "Please try again.",
        ["Info_FileNotFoundTitle"] = "File not found",
        ["Info_FileNotFoundMsg"] = "This program no longer exists at the saved location. It may have been moved or uninstalled.",

        // Activity page
        ["Act_Subtitle"] = "A local record of unlocks, denials and changes. Never leaves this device.",
        ["Act_Clear"] = "Clear history",
        ["Act_EmptyTitle"] = "No activity yet",
        ["Act_EmptySub"] = "Unlocks and changes will appear here.",
        ["Act_ClearTitle"] = "Clear activity history?",
        ["Act_ClearMsg"] = "This permanently removes the local record of unlocks and changes.",
        ["Act_Unlocked"] = "Unlocked {0}",
        ["Act_Denied"] = "Denied access to {0}",
        ["Act_Cancelled"] = "Cancelled opening {0}",
        ["Act_Relocked"] = "Re-locked {0}",
        ["Act_ProtEnabled"] = "Protection enabled",
        ["Act_ProtPaused"] = "Protection paused",
        ["Act_Protected"] = "Protected {0}",
        ["Act_Removed"] = "Removed protection from {0}",
        ["Act_MasterChanged"] = "Master password changed",
        ["Act_SettingsUpdated"] = "Settings updated",
        ["Act_ServiceStarted"] = "Protection service started",
        ["Act_ServiceStopped"] = "Protection service stopped",
        ["Act_Problem"] = "A problem occurred",
        ["Time_JustNow"] = "just now",
        ["Time_MinAgo"] = "{0} min ago",
        ["Time_Yesterday"] = "yesterday {0}",

        // Global protection toggle
        ["Confirm_PauseAllTitle"] = "Pause all protection?",
        ["Confirm_PauseAllMsg"] = "Every protected app will open without asking for your password until you turn protection back on.",
        ["Confirm_PauseAllBtn"] = "Pause protection",
        ["Err_ProtectionTitle"] = "Couldn't update protection",

        // Re-auth dialog
        ["ReAuth_Title"] = "Confirm it's you",
        ["ReAuth_Sub"] = "Enter your master password to change protection settings.",
        ["ReAuth_EnterPwd"] = "Enter your password.",

        // Confirm defaults
        ["Confirm_Title"] = "Are you sure?",

        // Protect dialog
        ["Protect_Title"] = "Protect an application",
        ["Protect_Sub"] = "Pick an installed app, or browse for a program.",
        ["Protect_SetupTitle"] = "Set up protection",
        ["Protect_SetupSub"] = "Choose how often Bastion should ask for your password.",
        ["Protect_SearchApps"] = "Search applications…",
        ["Protect_Scanning"] = "Scanning installed apps…",
        ["Protect_NoApps"] = "No installed apps found. Use Browse to pick a program.",
        ["Protect_Browse"] = "Browse for a program (.exe)  —  or drop one here",
        ["Protect_ChooseTitle"] = "Choose a program to protect",
        ["Protect_Unlock"] = "Unlock behaviour",
        ["Protect_Protecting"] = "Protecting…",
        ["Protect_Btn"] = "Protect",
        ["Protect_ErrTitle"] = "Couldn't protect this app",
        ["Warn_Store"] = "This looks like a Windows Store app. It may open through a system alias Bastion can't intercept — protection works best with classic desktop apps.",

        // Unlock behaviour combo (shared)
        ["Mode_Always"] = "Ask every time it opens",
        ["Mode_UntilClose"] = "Ask again once it fully closes",
        ["Mode_Minutes"] = "Stay unlocked for a few minutes",
        ["Mode_Session"] = "Stay unlocked until I sign out",
        ["Minutes_Keep"] = "Keep unlocked for",
        ["Minutes_1"] = "1 minute",
        ["Minutes_N"] = "{0} minutes",
        ["Hello_Allow"] = "Allow Windows Hello",
        ["Hello_AllowSub"] = "Unlock with PIN, fingerprint or face.",

        // Policy dialog
        ["Policy_Title"] = "Configure protection",
        ["Policy_RelockLock"] = "Re-lock when I lock Windows",
        ["Policy_RelockLockSub"] = "Require the password again after Win+L.",
        ["Policy_RelockSleep"] = "Re-lock after sleep",
        ["Policy_RelockSleepSub"] = "Require the password again after resuming.",
        ["Err_SaveTitle"] = "Couldn't save",

        // Change password dialog
        ["ChPwd_Title"] = "Change master password",
        ["ChPwd_Sub"] = "You'll use the new password to unlock apps.",
        ["ChPwd_Current"] = "Current password",
        ["ChPwd_New"] = "New password",
        ["ChPwd_Confirm"] = "Confirm new password",
        ["ChPwd_Update"] = "Update password",
        ["ChPwd_TooShort"] = "Choose a password with at least 6 characters.",
        ["ChPwd_Mismatch"] = "The new passwords don't match.",
        ["ChPwd_WrongCurrent"] = "Your current password is incorrect.",
        ["ChPwd_Failed"] = "Couldn't change the password.",

        // Recovery dialog
        ["Rec_Title"] = "Password recovery",
        ["Rec_Sub"] = "If you forget your master password, answer this question to set a new one. Stored only on this device.",
        ["Rec_Question"] = "Security question",
        ["Rec_Answer"] = "Answer",
        ["Rec_TurnOff"] = "Turn off recovery",
        ["Rec_NeedQuestion"] = "Enter a security question.",
        ["Rec_NeedAnswer"] = "Enter an answer.",
        ["Rec_Failed"] = "Couldn't save recovery.",
        ["Rec_OffFailed"] = "Couldn't turn off recovery.",

        // Settings
        ["Set_Security"] = "Security",
        ["Set_Master"] = "Master password",
        ["Set_MasterSub"] = "Used to unlock apps and confirm changes.",
        ["Set_Hello"] = "Windows Hello",
        ["Set_HelloSub"] = "Unlock with PIN, fingerprint or face instead of typing.",
        ["Set_HelloUnavailable"] = "Not available on this device.",
        ["Set_DefaultBehaviour"] = "Default unlock behaviour",
        ["Set_DefaultBehaviourSub"] = "Applied to apps that don't set their own.",
        ["Set_RequirePwd"] = "Require my password to change protection",
        ["Set_RequirePwdSub"] = "Removing apps or pausing protection asks for the password.",
        ["Set_Recovery"] = "Recovery",
        ["Set_RecoverySub"] = "Reset your master password with a security question.",
        ["Set_RecoveryOnSub"] = "Recovery is on. You can reset your password with your security answer.",
        ["Set_Lockout"] = "Lock out after wrong attempts",
        ["Set_LockoutSub"] = "Slows down guessing at the unlock prompt.",
        ["Set_Tries"] = "{0} tries",
        ["Set_Seconds"] = "{0} sec",
        ["Set_Application"] = "Application",
        ["Set_StartWin"] = "Start with Windows",
        ["Set_StartMin"] = "Start minimized to tray",
        ["Set_CloseTray"] = "Close button minimizes to tray",
        ["Set_Appearance"] = "Appearance",
        ["Set_Language"] = "Language",
        ["Theme_System"] = "Match Windows",
        ["Theme_Light"] = "Light",
        ["Theme_Dark"] = "Dark",
        ["Lang_System"] = "Match Windows",
        ["Lang_En"] = "English",
        ["Lang_Pt"] = "Português (Brasil)",
        ["Behaviour_Short_UntilClose"] = "Ask again once it closes",
        ["Behaviour_Short_Minutes"] = "Stay unlocked a few minutes",
        ["Behaviour_Short_Session"] = "Until I sign out",
        ["Set_Privacy"] = "Privacy",
        ["Set_KeepHistory"] = "Keep a local activity history",
        ["Set_KeepHistorySub"] = "Stored only on this device. Never uploaded.",
        ["Set_ClearHistory"] = "Clear activity history",
        ["Set_About"] = "About",
        ["Set_AboutVersion"] = "Application Lock · version {0}",
        ["Set_AboutBlurb"] = "Bastion keeps your chosen applications from opening without your authorization. Protection runs as a Windows service, independently of this window.",
        ["Set_Licence"] = "Licence",
        ["Set_HowItWorks"] = "How protection works",
        ["Set_HelloUnavailTitle"] = "Windows Hello unavailable",
        ["Set_HelloUnavailMsg"] = "Set up a PIN, fingerprint or face in Windows settings first.",
        ["Set_HelloLinkPrompt"] = "Enter your master password to link Windows Hello.",
        ["Set_HelloWrongTitle"] = "Incorrect password",
        ["Set_HelloWrongMsg"] = "Windows Hello was not linked.",
        ["Set_DocInstalled"] = "This document is included with the installed product.",

        // Onboarding
        ["Onb_WelcomeTitle"] = "Welcome to Bastion",
        ["Onb_WelcomeSub"] = "A quiet, dependable lock for the apps you choose. Nothing opens them without your authorization.",
        ["Onb_GetStarted"] = "Get started",
        ["Onb_HowTitle"] = "How protection works",
        ["Onb_How1Title"] = "Choose your apps",
        ["Onb_How1Sub"] = "Pick any installed program, or add an .exe yourself.",
        ["Onb_How2Title"] = "Every launch is intercepted",
        ["Onb_How2Sub"] = "From the desktop, Start menu, taskbar or the file itself — Windows itself redirects it to Bastion first.",
        ["Onb_How3Title"] = "You authorize, it opens",
        ["Onb_How3Sub"] = "Enter your password or use Windows Hello. Wrong answer, and it stays shut.",
        ["Onb_PwdTitle"] = "Create your master password",
        ["Onb_PwdSub"] = "This one password unlocks your protected apps. Choose something you'll remember — there's no way to read it back.",
        ["Onb_PwdCreate"] = "Create password",
        ["Onb_RecTitle"] = "Set up recovery (optional)",
        ["Onb_RecSub"] = "A security question lets you reset your password if you forget it. It stays on this device.",
        ["Onb_DoneTitle"] = "You're protected",
        ["Onb_DoneSub"] = "Add your first app and it won't open without you.",
        ["Onb_Open"] = "Open Bastion",
        ["Onb_PwdShort"] = "Use at least 6 characters.",
        ["Onb_PwdMismatch"] = "The passwords don't match.",
        ["Onb_ServiceDown"] = "The protection service isn't running. Restart the PC or run the installer again, then try again.",
        ["Onb_PwdFailed"] = "Couldn't set the password.",

        ["Err_Something"] = "Something went wrong",
    };

    public static readonly Dictionary<string, string> Pt = new()
    {
        // Common
        ["Common_Cancel"] = "Cancelar",
        ["Common_Confirm"] = "Confirmar",
        ["Common_Save"] = "Salvar",
        ["Common_Remove"] = "Remover",
        ["Common_Ok"] = "OK",
        ["Common_Done"] = "Concluir",
        ["Common_Back"] = "Voltar",
        ["Common_Continue"] = "Continuar",
        ["Common_Skip"] = "Pular",
        ["Common_Change"] = "Alterar",
        ["Common_SetUp"] = "Configurar",
        ["Common_Manage"] = "Gerenciar",
        ["Common_Clear"] = "Limpar",
        ["Common_Pause"] = "Pausar",

        // Gatekeeper
        ["GK_Subtitle"] = "Este aplicativo está protegido. Digite sua senha para abri-lo.",
        ["GK_Placeholder"] = "Senha",
        ["GK_Unlock"] = "Desbloquear",
        ["GK_Verifying"] = "Verificando…",
        ["GK_Identity"] = "Identidade confirmada",
        ["GK_UseHello"] = "Usar o Windows Hello",
        ["GK_Footer"] = "Protegido pelo Bastion",
        ["GK_Locked"] = "Bloqueado",
        ["GK_UnavailableSub"] = "A proteção está temporariamente indisponível. Tente novamente em instantes.",
        ["GK_UnavailableErr"] = "O serviço de proteção não está respondendo.",
        ["GK_Incorrect"] = "Senha incorreta.",
        ["GK_HelloFailed"] = "O Windows Hello não foi confirmado.",
        ["GK_CouldNotOpen"] = "Não foi possível abrir o aplicativo.",
        ["GK_TooMany"] = "Tentativas demais. Tente novamente em {0}s.",

        // Nav / shell
        ["Nav_Home"] = "Início",
        ["Nav_Apps"] = "Aplicativos",
        ["Nav_Activity"] = "Atividade",
        ["Nav_Settings"] = "Configurações",
        ["Status_Active"] = "Proteção ativa",
        ["Status_Offline"] = "Serviço offline",
        ["Status_NoApps"] = "Nenhum app protegido",
        ["Status_Paused"] = "Proteção pausada",
        ["GlobalProtection"] = "Proteção global",
        ["Banner_ServiceDown"] = "O serviço de proteção do Bastion não está respondendo. A proteção pode estar inativa.",
        ["Tip_Minimize"] = "Minimizar",
        ["Tip_CloseTray"] = "Fechar para a bandeja",

        // Tray
        ["Tray_Open"] = "Abrir o Bastion",
        ["Tray_RelockAll"] = "Bloquear todos os apps agora",
        ["Tray_Settings"] = "Configurações",
        ["Tray_Exit"] = "Sair do painel (a proteção continua ativa)",
        ["Tray_Tooltip"] = "Bastion — Bloqueio de Aplicativos",

        // Home
        ["Home_CountNone"] = "Nada protegido ainda",
        ["Home_CountOne"] = "1 app protegido",
        ["Home_CountN"] = "{0} apps protegidos",
        ["Home_SubNone"] = "Escolha um app e ele não abrirá sem a sua senha.",
        ["Home_SubSome"] = "Estes apps pedem a sua senha antes de abrir.",
        ["Home_Protect"] = "Proteger um aplicativo",
        ["Home_ProtectedApps"] = "Aplicativos protegidos",
        ["Home_EmptyTitle"] = "Nada protegido ainda",
        ["Home_EmptySub"] = "Adicione seu primeiro app para exigir a senha antes de abrir.",
        ["Home_Recent"] = "Atividade recente",
        ["Home_NoActivity"] = "Nenhuma atividade ainda.",

        // Status pills / policy
        ["Pill_Paused"] = "Pausado",
        ["Pill_Unlocked"] = "Desbloqueado",
        ["Pill_Protected"] = "Protegido",
        ["Policy_Always"] = "Pede a senha toda vez que abre",
        ["Policy_UntilClose"] = "Bloqueia de novo quando fecha",
        ["Policy_Minutes"] = "Fica desbloqueado por {0} min",
        ["Policy_Session"] = "Desbloqueado até você sair do Windows",

        // Applications page
        ["Apps_Search"] = "Buscar apps protegidos…",
        ["Apps_Add"] = "Proteger um app",
        ["Apps_EmptyTitle"] = "Nenhum app protegido",
        ["Apps_EmptySub"] = "Use “Proteger um app” para adicionar o primeiro.",
        ["Tip_OnOff"] = "Proteção ligada/desligada",
        ["Tip_Configure"] = "Configurar",
        ["Tip_OpenLocation"] = "Abrir local do arquivo",
        ["Tip_Remove"] = "Remover proteção",
        ["Confirm_PauseAppTitle"] = "Pausar a proteção de {0}?",
        ["Confirm_PauseAppMsg"] = "Ele vai abrir sem senha até você reativar a proteção.",
        ["Confirm_RemoveTitle"] = "Remover a proteção de {0}?",
        ["Confirm_RemoveMsg"] = "Este app vai abrir normalmente, sem pedir a sua senha.",
        ["Err_UpdateTitle"] = "Não foi possível atualizar",
        ["Err_RemoveTitle"] = "Não foi possível remover",
        ["Err_Generic"] = "Tente novamente.",
        ["Info_FileNotFoundTitle"] = "Arquivo não encontrado",
        ["Info_FileNotFoundMsg"] = "Este programa não existe mais no local salvo. Ele pode ter sido movido ou desinstalado.",

        // Activity
        ["Act_Subtitle"] = "Um registro local de desbloqueios, negações e alterações. Nunca sai deste dispositivo.",
        ["Act_Clear"] = "Limpar histórico",
        ["Act_EmptyTitle"] = "Nenhuma atividade ainda",
        ["Act_EmptySub"] = "Desbloqueios e alterações aparecerão aqui.",
        ["Act_ClearTitle"] = "Limpar o histórico de atividade?",
        ["Act_ClearMsg"] = "Isso remove permanentemente o registro local de desbloqueios e alterações.",
        ["Act_Unlocked"] = "{0} desbloqueado",
        ["Act_Denied"] = "Acesso negado a {0}",
        ["Act_Cancelled"] = "Abertura de {0} cancelada",
        ["Act_Relocked"] = "{0} bloqueado novamente",
        ["Act_ProtEnabled"] = "Proteção ativada",
        ["Act_ProtPaused"] = "Proteção pausada",
        ["Act_Protected"] = "{0} protegido",
        ["Act_Removed"] = "Proteção removida de {0}",
        ["Act_MasterChanged"] = "Senha principal alterada",
        ["Act_SettingsUpdated"] = "Configurações atualizadas",
        ["Act_ServiceStarted"] = "Serviço de proteção iniciado",
        ["Act_ServiceStopped"] = "Serviço de proteção parado",
        ["Act_Problem"] = "Ocorreu um problema",
        ["Time_JustNow"] = "agora mesmo",
        ["Time_MinAgo"] = "há {0} min",
        ["Time_Yesterday"] = "ontem {0}",

        // Global protection
        ["Confirm_PauseAllTitle"] = "Pausar toda a proteção?",
        ["Confirm_PauseAllMsg"] = "Todos os apps protegidos vão abrir sem pedir a sua senha até você reativar a proteção.",
        ["Confirm_PauseAllBtn"] = "Pausar proteção",
        ["Err_ProtectionTitle"] = "Não foi possível atualizar a proteção",

        // Re-auth
        ["ReAuth_Title"] = "Confirme que é você",
        ["ReAuth_Sub"] = "Digite sua senha principal para alterar as configurações de proteção.",
        ["ReAuth_EnterPwd"] = "Digite sua senha.",

        ["Confirm_Title"] = "Tem certeza?",

        // Protect dialog
        ["Protect_Title"] = "Proteger um aplicativo",
        ["Protect_Sub"] = "Escolha um app instalado ou procure um programa.",
        ["Protect_SetupTitle"] = "Configurar a proteção",
        ["Protect_SetupSub"] = "Escolha com que frequência o Bastion deve pedir a sua senha.",
        ["Protect_SearchApps"] = "Buscar aplicativos…",
        ["Protect_Scanning"] = "Buscando apps instalados…",
        ["Protect_NoApps"] = "Nenhum app instalado encontrado. Use Procurar para escolher um programa.",
        ["Protect_Browse"] = "Procurar um programa (.exe)  —  ou solte um aqui",
        ["Protect_ChooseTitle"] = "Escolha um programa para proteger",
        ["Protect_Unlock"] = "Comportamento de desbloqueio",
        ["Protect_Protecting"] = "Protegendo…",
        ["Protect_Btn"] = "Proteger",
        ["Protect_ErrTitle"] = "Não foi possível proteger este app",
        ["Warn_Store"] = "Isto parece um app da Microsoft Store. Ele pode abrir por um atalho do sistema que o Bastion não intercepta — a proteção funciona melhor com apps de desktop clássicos.",

        // Unlock combo
        ["Mode_Always"] = "Pedir a senha toda vez que abrir",
        ["Mode_UntilClose"] = "Pedir de novo depois que fechar",
        ["Mode_Minutes"] = "Ficar desbloqueado por alguns minutos",
        ["Mode_Session"] = "Ficar desbloqueado até eu sair do Windows",
        ["Minutes_Keep"] = "Manter desbloqueado por",
        ["Minutes_1"] = "1 minuto",
        ["Minutes_N"] = "{0} minutos",
        ["Hello_Allow"] = "Permitir o Windows Hello",
        ["Hello_AllowSub"] = "Desbloqueie com PIN, digital ou rosto.",

        // Policy dialog
        ["Policy_Title"] = "Configurar a proteção",
        ["Policy_RelockLock"] = "Bloquear ao bloquear o Windows",
        ["Policy_RelockLockSub"] = "Pedir a senha novamente após o Win+L.",
        ["Policy_RelockSleep"] = "Bloquear após suspensão",
        ["Policy_RelockSleepSub"] = "Pedir a senha novamente ao retomar.",
        ["Err_SaveTitle"] = "Não foi possível salvar",

        // Change password
        ["ChPwd_Title"] = "Alterar senha principal",
        ["ChPwd_Sub"] = "Você usará a nova senha para desbloquear os apps.",
        ["ChPwd_Current"] = "Senha atual",
        ["ChPwd_New"] = "Nova senha",
        ["ChPwd_Confirm"] = "Confirmar a nova senha",
        ["ChPwd_Update"] = "Atualizar senha",
        ["ChPwd_TooShort"] = "Escolha uma senha com pelo menos 6 caracteres.",
        ["ChPwd_Mismatch"] = "As novas senhas não coincidem.",
        ["ChPwd_WrongCurrent"] = "A sua senha atual está incorreta.",
        ["ChPwd_Failed"] = "Não foi possível alterar a senha.",

        // Recovery
        ["Rec_Title"] = "Recuperação de senha",
        ["Rec_Sub"] = "Se você esquecer a senha principal, responda esta pergunta para definir uma nova. Fica apenas neste dispositivo.",
        ["Rec_Question"] = "Pergunta de segurança",
        ["Rec_Answer"] = "Resposta",
        ["Rec_TurnOff"] = "Desativar recuperação",
        ["Rec_NeedQuestion"] = "Digite uma pergunta de segurança.",
        ["Rec_NeedAnswer"] = "Digite uma resposta.",
        ["Rec_Failed"] = "Não foi possível salvar a recuperação.",
        ["Rec_OffFailed"] = "Não foi possível desativar a recuperação.",

        // Settings
        ["Set_Security"] = "Segurança",
        ["Set_Master"] = "Senha principal",
        ["Set_MasterSub"] = "Usada para desbloquear apps e confirmar alterações.",
        ["Set_Hello"] = "Windows Hello",
        ["Set_HelloSub"] = "Desbloqueie com PIN, digital ou rosto em vez de digitar.",
        ["Set_HelloUnavailable"] = "Não disponível neste dispositivo.",
        ["Set_DefaultBehaviour"] = "Comportamento de desbloqueio padrão",
        ["Set_DefaultBehaviourSub"] = "Aplicado a apps que não definem o próprio.",
        ["Set_RequirePwd"] = "Exigir minha senha para alterar a proteção",
        ["Set_RequirePwdSub"] = "Remover apps ou pausar a proteção pede a senha.",
        ["Set_Recovery"] = "Recuperação",
        ["Set_RecoverySub"] = "Redefina sua senha principal com uma pergunta de segurança.",
        ["Set_RecoveryOnSub"] = "A recuperação está ativa. Você pode redefinir a senha com sua resposta de segurança.",
        ["Set_Lockout"] = "Bloquear após tentativas erradas",
        ["Set_LockoutSub"] = "Dificulta tentativas de adivinhar na tela de desbloqueio.",
        ["Set_Tries"] = "{0} tentativas",
        ["Set_Seconds"] = "{0} seg",
        ["Set_Application"] = "Aplicativo",
        ["Set_StartWin"] = "Iniciar com o Windows",
        ["Set_StartMin"] = "Iniciar minimizado na bandeja",
        ["Set_CloseTray"] = "Botão fechar minimiza para a bandeja",
        ["Set_Appearance"] = "Aparência",
        ["Set_Language"] = "Idioma",
        ["Theme_System"] = "Acompanhar o Windows",
        ["Theme_Light"] = "Claro",
        ["Theme_Dark"] = "Escuro",
        ["Lang_System"] = "Acompanhar o Windows",
        ["Lang_En"] = "English",
        ["Lang_Pt"] = "Português (Brasil)",
        ["Behaviour_Short_UntilClose"] = "Pedir de novo ao fechar",
        ["Behaviour_Short_Minutes"] = "Desbloqueado por alguns min",
        ["Behaviour_Short_Session"] = "Até eu sair do Windows",
        ["Set_Privacy"] = "Privacidade",
        ["Set_KeepHistory"] = "Manter um histórico local de atividade",
        ["Set_KeepHistorySub"] = "Guardado só neste dispositivo. Nunca é enviado.",
        ["Set_ClearHistory"] = "Limpar o histórico de atividade",
        ["Set_About"] = "Sobre",
        ["Set_AboutVersion"] = "Bloqueio de Aplicativos · versão {0}",
        ["Set_AboutBlurb"] = "O Bastion impede que os aplicativos escolhidos abram sem a sua autorização. A proteção roda como um serviço do Windows, de forma independente desta janela.",
        ["Set_Licence"] = "Licença",
        ["Set_HowItWorks"] = "Como a proteção funciona",
        ["Set_HelloUnavailTitle"] = "Windows Hello indisponível",
        ["Set_HelloUnavailMsg"] = "Configure um PIN, digital ou rosto nas configurações do Windows primeiro.",
        ["Set_HelloLinkPrompt"] = "Digite sua senha principal para vincular o Windows Hello.",
        ["Set_HelloWrongTitle"] = "Senha incorreta",
        ["Set_HelloWrongMsg"] = "O Windows Hello não foi vinculado.",
        ["Set_DocInstalled"] = "Este documento acompanha o produto instalado.",

        // Onboarding
        ["Onb_WelcomeTitle"] = "Bem-vindo ao Bastion",
        ["Onb_WelcomeSub"] = "Um bloqueio discreto e confiável para os apps que você escolher. Nada os abre sem a sua autorização.",
        ["Onb_GetStarted"] = "Começar",
        ["Onb_HowTitle"] = "Como a proteção funciona",
        ["Onb_How1Title"] = "Escolha seus apps",
        ["Onb_How1Sub"] = "Escolha qualquer programa instalado, ou adicione um .exe você mesmo.",
        ["Onb_How2Title"] = "Toda abertura é interceptada",
        ["Onb_How2Sub"] = "Da área de trabalho, Menu Iniciar, barra de tarefas ou do próprio arquivo — o Windows redireciona para o Bastion primeiro.",
        ["Onb_How3Title"] = "Você autoriza, e ele abre",
        ["Onb_How3Sub"] = "Digite sua senha ou use o Windows Hello. Resposta errada, e ele continua fechado.",
        ["Onb_PwdTitle"] = "Crie sua senha principal",
        ["Onb_PwdSub"] = "Esta única senha desbloqueia seus apps protegidos. Escolha algo que você lembre — não há como recuperá-la.",
        ["Onb_PwdCreate"] = "Criar senha",
        ["Onb_RecTitle"] = "Configurar recuperação (opcional)",
        ["Onb_RecSub"] = "Uma pergunta de segurança permite redefinir a senha se você esquecê-la. Fica neste dispositivo.",
        ["Onb_DoneTitle"] = "Você está protegido",
        ["Onb_DoneSub"] = "Adicione seu primeiro app e ele não abrirá sem você.",
        ["Onb_Open"] = "Abrir o Bastion",
        ["Onb_PwdShort"] = "Use pelo menos 6 caracteres.",
        ["Onb_PwdMismatch"] = "As senhas não coincidem.",
        ["Onb_ServiceDown"] = "O serviço de proteção não está em execução. Reinicie o PC ou execute o instalador de novo e tente novamente.",
        ["Onb_PwdFailed"] = "Não foi possível definir a senha.",

        ["Err_Something"] = "Algo deu errado",
    };
}
